/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author shreyamalapaka
 */


public class HuskyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HuskyJFrame
     */
    
    private Person person;
    
    public HuskyJFrame() {
        initComponents();
        
        this.person = new Person();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        HuskyViewJPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        viewNUID = new javax.swing.JLabel();
        viewFirstName = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewClgName = new javax.swing.JLabel();
        viewOffPhone = new javax.swing.JLabel();
        viewOffEmail = new javax.swing.JLabel();
        viewPersPhone = new javax.swing.JLabel();
        viewPersEmail = new javax.swing.JLabel();
        viewCurrStreet = new javax.swing.JLabel();
        viewCurrApt = new javax.swing.JLabel();
        viewCurrCity = new javax.swing.JLabel();
        viewCurrZip = new javax.swing.JLabel();
        viewPermStreet = new javax.swing.JLabel();
        viewPermApt = new javax.swing.JLabel();
        viewPermCity = new javax.swing.JLabel();
        viewPermZip = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        HuskyInputJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldClgName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fieldOffPhone = new javax.swing.JTextField();
        fieldOffEmail = new javax.swing.JTextField();
        fieldPersPhone = new javax.swing.JTextField();
        fieldPersEmail = new javax.swing.JTextField();
        fieldCurrStreet = new javax.swing.JTextField();
        fieldCurrApt = new javax.swing.JTextField();
        fieldCurrCity = new javax.swing.JTextField();
        fieldCurrZip = new javax.swing.JTextField();
        fieldPermStreet = new javax.swing.JTextField();
        fieldPermApt = new javax.swing.JTextField();
        fieldPermCity = new javax.swing.JTextField();
        fieldPermZip = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HuskyViewJPanel.setBackground(new java.awt.Color(0, 204, 204));

        jLabel21.setText("NUID:");

        jLabel22.setText("First Name:");

        jLabel23.setText("Last Name:");

        jLabel24.setText("College Name:");

        jLabel25.setText("Contact - Office");

        jLabel26.setText("Phone:");

        jLabel27.setText("Email Id:");

        jLabel28.setText("Contact - Personal:");

        jLabel29.setText("Phone:");

        jLabel30.setText("Email Id:");

        jLabel31.setText("Current Address:");

        jLabel32.setText("Street:");

        jLabel33.setText("Apt. No:");

        jLabel34.setText("City/State:");

        jLabel35.setText("Zip Code:");

        jLabel36.setText("Permanent Address:");

        jLabel37.setText("Street:");

        jLabel38.setText("Apt. No:");

        jLabel39.setText("City/State:");

        jLabel40.setText("Zip Code:");

        jLabel41.setText("Husky Card");

        javax.swing.GroupLayout HuskyViewJPanelLayout = new javax.swing.GroupLayout(HuskyViewJPanel);
        HuskyViewJPanel.setLayout(HuskyViewJPanelLayout);
        HuskyViewJPanelLayout.setHorizontalGroup(
            HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HuskyViewJPanelLayout.createSequentialGroup()
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HuskyViewJPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel34))
                        .addGap(73, 73, 73)
                        .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewNUID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewClgName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewOffPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewOffEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPersPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPersEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCurrStreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCurrApt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCurrCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCurrZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPermStreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPermApt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPermCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPermZip, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                    .addGroup(HuskyViewJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel41)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HuskyViewJPanelLayout.setVerticalGroup(
            HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HuskyViewJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addGap(2, 2, 2)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(viewNUID))
                .addGap(18, 18, 18)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(viewFirstName))
                .addGap(18, 18, 18)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(viewLastName))
                .addGap(18, 18, 18)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(viewClgName))
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(12, 12, 12)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(viewOffPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(viewOffEmail))
                .addGap(30, 30, 30)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(viewPersPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(viewPersEmail))
                .addGap(26, 26, 26)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(viewCurrStreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(viewCurrApt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(viewCurrCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(viewCurrZip))
                .addGap(27, 27, 27)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(viewPermStreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(viewPermApt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(viewPermCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HuskyViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(viewPermZip))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(HuskyViewJPanel);

        HuskyInputJPanel.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("NUID:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("College Name:");

        jLabel5.setText("Contact-Office:");

        fieldNUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNUIDActionPerformed(evt);
            }
        });

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });

        jLabel6.setText("Phone:");

        jLabel7.setText("Email id:");

        jLabel8.setText("Contact-Personal:");

        jLabel9.setText("Phone:");

        jLabel10.setText("Email id:");

        jLabel11.setText("Current Address:");

        jLabel12.setText("Street:");

        jLabel13.setText("Apt. No:");

        jLabel14.setText("City/State:");

        jLabel15.setText("Zip Code:");

        jLabel16.setText("Permanent Address:");

        jLabel17.setText("Street:");

        jLabel18.setText("Apt. No:");

        jLabel19.setText("City/State:");

        jLabel20.setText("Zip Code:");

        fieldOffPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOffPhoneActionPerformed(evt);
            }
        });

        fieldCurrStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrStreetActionPerformed(evt);
            }
        });

        fieldCurrApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrAptActionPerformed(evt);
            }
        });

        fieldCurrCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrCityActionPerformed(evt);
            }
        });

        fieldPermStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermStreetActionPerformed(evt);
            }
        });

        fieldPermCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermCityActionPerformed(evt);
            }
        });

        fieldPermZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermZipActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HuskyInputJPanelLayout = new javax.swing.GroupLayout(HuskyInputJPanel);
        HuskyInputJPanel.setLayout(HuskyInputJPanelLayout);
        HuskyInputJPanelLayout.setHorizontalGroup(
            HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HuskyInputJPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldNUID)
                    .addComponent(fieldFirstName)
                    .addComponent(fieldLastName)
                    .addComponent(fieldClgName)
                    .addComponent(fieldOffPhone)
                    .addComponent(fieldOffEmail)
                    .addComponent(fieldPersPhone)
                    .addComponent(fieldPersEmail)
                    .addComponent(fieldCurrStreet)
                    .addComponent(fieldCurrApt)
                    .addComponent(fieldCurrCity)
                    .addComponent(fieldCurrZip, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(fieldPermZip, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(fieldPermCity)
                    .addComponent(fieldPermApt)
                    .addComponent(fieldPermStreet))
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HuskyInputJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        HuskyInputJPanelLayout.setVerticalGroup(
            HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HuskyInputJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HuskyInputJPanelLayout.createSequentialGroup()
                        .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(fieldClgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldOffPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldOffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldPersPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldPersEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(fieldCurrStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(fieldCurrApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(fieldCurrCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCurrZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HuskyInputJPanelLayout.createSequentialGroup()
                        .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(fieldPermStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(fieldPermApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addComponent(fieldPermCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HuskyInputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fieldPermZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(HuskyInputJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNUIDActionPerformed

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void fieldOffPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOffPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOffPhoneActionPerformed

    private void fieldCurrStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrStreetActionPerformed

    private void fieldCurrAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrAptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrAptActionPerformed

    private void fieldCurrCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrCityActionPerformed

    private void fieldPermStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermStreetActionPerformed

    private void fieldPermCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermCityActionPerformed

    private void fieldPermZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermZipActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        long nuid = Long.valueOf(fieldNUID.getText());
        String firstName = fieldFirstName.getText();
        String lastName = fieldLastName.getText();
        String clgName = fieldClgName.getText();
        
        long oPhone = Long.valueOf(fieldOffPhone.getText());
        String oEmail = fieldOffEmail.getText();
        
        long pPhone = Long.valueOf(fieldPersPhone.getText());
        String pEmail = fieldPersEmail.getText();
        
        String currStreet = fieldCurrStreet.getText();
        String currApt = fieldCurrApt.getText();
        String currCity = fieldCurrCity.getText();
        long currZip = Long.valueOf(fieldCurrZip.getText());
        
        String permStreet = fieldPermStreet.getText();
        String permApt = fieldPermApt.getText();
        String permCity = fieldPermCity.getText();
        long permZip = Long.valueOf(fieldPermZip.getText());
        
        
        
        this.person.setNuid(nuid);
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setClgName(clgName);
        
        Contact oContact = this.person.getoContact();
        oContact.setPhone(oPhone);
        oContact.setEmail(oEmail);
        
        Contact pContact = this.person.getpContact();
        pContact.setPhone(pPhone);
        pContact.setEmail(pEmail);
        
        Address currAddress = this.person.getCurrAddress();
        currAddress.setStreet(currStreet);
        currAddress.setApt(currApt);
        currAddress.setCity(currCity);
        currAddress.setZip(currZip);
        
        Address permAddress = this.person.getPermAddress();
        permAddress.setStreet(permStreet);
        permAddress.setApt(permApt);
        permAddress.setCity(permCity);
        permAddress.setZip(permZip);
        
        display();
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void display() {
        viewNUID.setText(String.valueOf(this.person.getNuid()));
        viewFirstName.setText(this.person.getFirstName());
        viewLastName.setText(this.person.getLastName());
        viewClgName.setText(this.person.getClgName());
        
        viewOffPhone.setText(String.valueOf(this.person.getoContact().getPhone()));
        viewOffEmail.setText(this.person.getoContact().getEmail());
        
        viewPersPhone.setText(String.valueOf(this.person.getpContact().getPhone()));
        viewPersEmail.setText(this.person.getpContact().getEmail());
        
        
        viewCurrStreet.setText(this.person.getCurrAddress().getStreet());
        viewCurrApt.setText(this.person.getCurrAddress().getApt());
        viewCurrCity.setText(this.person.getCurrAddress().getCity());
        viewCurrZip.setText(String.valueOf(this.person.getCurrAddress().getZip()));
        
        viewPermStreet.setText(this.person.getPermAddress().getStreet());
        viewPermApt.setText(this.person.getPermAddress().getApt());
        viewPermCity.setText(this.person.getPermAddress().getCity());
        viewPermZip.setText(String.valueOf(this.person.getPermAddress().getZip()));  
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuskyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuskyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuskyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuskyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuskyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HuskyInputJPanel;
    private javax.swing.JPanel HuskyViewJPanel;
    private javax.swing.JTextField fieldClgName;
    private javax.swing.JTextField fieldCurrApt;
    private javax.swing.JTextField fieldCurrCity;
    private javax.swing.JTextField fieldCurrStreet;
    private javax.swing.JTextField fieldCurrZip;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldOffEmail;
    private javax.swing.JTextField fieldOffPhone;
    private javax.swing.JTextField fieldPermApt;
    private javax.swing.JTextField fieldPermCity;
    private javax.swing.JTextField fieldPermStreet;
    private javax.swing.JTextField fieldPermZip;
    private javax.swing.JTextField fieldPersEmail;
    private javax.swing.JTextField fieldPersPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel viewClgName;
    private javax.swing.JLabel viewCurrApt;
    private javax.swing.JLabel viewCurrCity;
    private javax.swing.JLabel viewCurrStreet;
    private javax.swing.JLabel viewCurrZip;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewOffEmail;
    private javax.swing.JLabel viewOffPhone;
    private javax.swing.JLabel viewPermApt;
    private javax.swing.JLabel viewPermCity;
    private javax.swing.JLabel viewPermStreet;
    private javax.swing.JLabel viewPermZip;
    private javax.swing.JLabel viewPersEmail;
    private javax.swing.JLabel viewPersPhone;
    // End of variables declaration//GEN-END:variables
}
