/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author shreyamalapaka
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Application application;
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
        initComponents();
        
        this.application= application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldObsId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldTemp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldBloodPressure = new javax.swing.JTextField();
        addObsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create a Vital Sign");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 20, -1, -1));

        jLabel2.setText("ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 79, -1, -1));
        add(fieldObsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 74, 97, -1));

        jLabel3.setText("Temperature:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 123, -1, -1));
        add(fieldTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 118, 97, -1));

        jLabel4.setText("Blood Pressure:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 167, -1, -1));
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 162, 97, -1));

        addObsBtn.setText("Add Observation");
        addObsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObsBtnActionPerformed(evt);
            }
        });
        add(addObsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 228, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addObsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObsBtnActionPerformed
        // TODO add your handling code here:
        
        //add an obs to vital sign hist
        
        VitalSignHistory history = this.application.getHistory();
        
        //read the textfields
        String id = fieldObsId.getText();
        String temp = fieldTemp.getText();
        String bloodPressure = fieldBloodPressure.getText();
        
        
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(bloodPressure),  Double.valueOf(temp));
        
        JOptionPane.showMessageDialog(null,"Added");
    }//GEN-LAST:event_addObsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObsBtn;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldObsId;
    private javax.swing.JTextField fieldTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
