/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author shreyamalapaka
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    
    public CreateJPanel() {
        initComponents();
    }
    
    private DeliveryPackage delpackage;
    private Boolean validate = false;
    
    public CreateJPanel(DeliveryPackage deliverypackage) {
        initComponents();
        this.delpackage = deliverypackage;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageWt = new javax.swing.JTextField();
        productId1 = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice1 = new javax.swing.JTextField();
        custName1 = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        packageId = new javax.swing.JTextField();
        saveProdBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 66, 90, -1));
        add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, -1));
        add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 90, -1));

        productPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPrice1ActionPerformed(evt);
            }
        });
        add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 90, -1));

        custName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custName1ActionPerformed(evt);
            }
        });
        add(custName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 90, -1));

        custId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIdActionPerformed(evt);
            }
        });
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 90, -1));

        jLabel1.setText("Package ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 37, -1, -1));

        jLabel2.setText("weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 71, -1, -1));

        jLabel3.setText("prodId");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel4.setText("prodName");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setText("ProdPrice");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel6.setText("custname");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel7.setText("id");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, -1));

        saveProdBtn.setText("SAVE PRODUCT");
        saveProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProdBtnActionPerformed(evt);
            }
        });
        add(saveProdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void productPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPrice1ActionPerformed

    private void custName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custName1ActionPerformed

    private void custIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIdActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String id = packageId.getText();
        String weight = packageWt.getText();
        String customerName = custName1.getText();
        String customerId = custId.getText();
        
        this.delpackage.setPackageId(Integer.valueOf(id));
        this.delpackage.setPackageWeight(Double.valueOf(weight));
        
        
        
        Customer customer = this.delpackage.getCustomer();
        customer.setCustId(Integer.valueOf(customerId));
        customer.setFullName(customerName);
        
        if(validate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else {
            JOptionPane.showMessageDialog(null, "Saved!");
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void saveProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProdBtnActionPerformed
        // TODO add your handling code here:
        String productId = productId1.getText();
        String productName = productName1.getText();
        String productPrice = productPrice1.getText();
        

        
        Product product = this.delpackage.createProd(Integer.valueOf(productId), productName, Double.valueOf(productPrice));
        
        JOptionPane.showMessageDialog(null, "SAVED PRODUCT");
    }//GEN-LAST:event_saveProdBtnActionPerformed

    private void custLost(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        
        System.out.println(custName1.getText() + " -- the customer name");
        String name = custName1.getText();
        
        if(name.isEmpty()) {

            this.validate = true;
        } else {
            this.validate = false;
        }
    }          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton saveProdBtn;
    // End of variables declaration//GEN-END:variables
}
